/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.tutorial.Feature');

goog.require('jspb.Message');
goog.require('proto.tutorial.TcCircularHoleSerializable');
goog.require('proto.tutorial.TcCuttingContourSerializable');
goog.require('proto.tutorial.TcDoubleChamferSerializable');
goog.require('proto.tutorial.TcElongatedHoleSerializable');
goog.require('proto.tutorial.TcRectangularHoleSerializable');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.tutorial.Feature = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.tutorial.Feature.oneofGroups_);
};
goog.inherits(proto.tutorial.Feature, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.tutorial.Feature.displayName = 'proto.tutorial.Feature';
}
/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.tutorial.Feature.oneofGroups_ = [[1,2,3,4,5]];

/**
 * @enum {number}
 */
proto.tutorial.Feature.FeatureCase = {
  FEATURE_NOT_SET: 0,
  CIRCULARHOLE: 1,
  CUTTINGCONTOUR: 2,
  RECTANGULARHOLE: 3,
  ELONGATEDHOLE: 4,
  DOUBLECHAMFER: 5
};

/**
 * @return {proto.tutorial.Feature.FeatureCase}
 */
proto.tutorial.Feature.prototype.getFeatureCase = function() {
  return /** @type {proto.tutorial.Feature.FeatureCase} */(jspb.Message.computeOneofCase(this, proto.tutorial.Feature.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.tutorial.Feature.prototype.toObject = function(opt_includeInstance) {
  return proto.tutorial.Feature.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.tutorial.Feature} msg The msg instance to transform.
 * @return {!Object}
 */
proto.tutorial.Feature.toObject = function(includeInstance, msg) {
  var f, obj = {
    circularhole: (f = msg.getCircularhole()) && proto.tutorial.TcCircularHoleSerializable.toObject(includeInstance, f),
    cuttingcontour: (f = msg.getCuttingcontour()) && proto.tutorial.TcCuttingContourSerializable.toObject(includeInstance, f),
    rectangularhole: (f = msg.getRectangularhole()) && proto.tutorial.TcRectangularHoleSerializable.toObject(includeInstance, f),
    elongatedhole: (f = msg.getElongatedhole()) && proto.tutorial.TcElongatedHoleSerializable.toObject(includeInstance, f),
    doublechamfer: (f = msg.getDoublechamfer()) && proto.tutorial.TcDoubleChamferSerializable.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg
  }
  return obj;
};
}


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.tutorial.Feature} The clone.
 */
proto.tutorial.Feature.prototype.cloneMessage = function() {
  return /** @type {!proto.tutorial.Feature} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional TcCircularHoleSerializable CircularHole = 1;
 * @return {proto.tutorial.TcCircularHoleSerializable}
 */
proto.tutorial.Feature.prototype.getCircularhole = function() {
  return /** @type{proto.tutorial.TcCircularHoleSerializable} */ (
    jspb.Message.getWrapperField(this, proto.tutorial.TcCircularHoleSerializable, 1));
};


/** @param {proto.tutorial.TcCircularHoleSerializable|undefined} value  */
proto.tutorial.Feature.prototype.setCircularhole = function(value) {
  jspb.Message.setOneofWrapperField(this, 1, proto.tutorial.Feature.oneofGroups_[0], value);
};


proto.tutorial.Feature.prototype.clearCircularhole = function() {
  this.setCircularhole(undefined);
};


/**
 * optional TcCuttingContourSerializable CuttingContour = 2;
 * @return {proto.tutorial.TcCuttingContourSerializable}
 */
proto.tutorial.Feature.prototype.getCuttingcontour = function() {
  return /** @type{proto.tutorial.TcCuttingContourSerializable} */ (
    jspb.Message.getWrapperField(this, proto.tutorial.TcCuttingContourSerializable, 2));
};


/** @param {proto.tutorial.TcCuttingContourSerializable|undefined} value  */
proto.tutorial.Feature.prototype.setCuttingcontour = function(value) {
  jspb.Message.setOneofWrapperField(this, 2, proto.tutorial.Feature.oneofGroups_[0], value);
};


proto.tutorial.Feature.prototype.clearCuttingcontour = function() {
  this.setCuttingcontour(undefined);
};


/**
 * optional TcRectangularHoleSerializable RectangularHole = 3;
 * @return {proto.tutorial.TcRectangularHoleSerializable}
 */
proto.tutorial.Feature.prototype.getRectangularhole = function() {
  return /** @type{proto.tutorial.TcRectangularHoleSerializable} */ (
    jspb.Message.getWrapperField(this, proto.tutorial.TcRectangularHoleSerializable, 3));
};


/** @param {proto.tutorial.TcRectangularHoleSerializable|undefined} value  */
proto.tutorial.Feature.prototype.setRectangularhole = function(value) {
  jspb.Message.setOneofWrapperField(this, 3, proto.tutorial.Feature.oneofGroups_[0], value);
};


proto.tutorial.Feature.prototype.clearRectangularhole = function() {
  this.setRectangularhole(undefined);
};


/**
 * optional TcElongatedHoleSerializable ElongatedHole = 4;
 * @return {proto.tutorial.TcElongatedHoleSerializable}
 */
proto.tutorial.Feature.prototype.getElongatedhole = function() {
  return /** @type{proto.tutorial.TcElongatedHoleSerializable} */ (
    jspb.Message.getWrapperField(this, proto.tutorial.TcElongatedHoleSerializable, 4));
};


/** @param {proto.tutorial.TcElongatedHoleSerializable|undefined} value  */
proto.tutorial.Feature.prototype.setElongatedhole = function(value) {
  jspb.Message.setOneofWrapperField(this, 4, proto.tutorial.Feature.oneofGroups_[0], value);
};


proto.tutorial.Feature.prototype.clearElongatedhole = function() {
  this.setElongatedhole(undefined);
};


/**
 * optional TcDoubleChamferSerializable DoubleChamfer = 5;
 * @return {proto.tutorial.TcDoubleChamferSerializable}
 */
proto.tutorial.Feature.prototype.getDoublechamfer = function() {
  return /** @type{proto.tutorial.TcDoubleChamferSerializable} */ (
    jspb.Message.getWrapperField(this, proto.tutorial.TcDoubleChamferSerializable, 5));
};


/** @param {proto.tutorial.TcDoubleChamferSerializable|undefined} value  */
proto.tutorial.Feature.prototype.setDoublechamfer = function(value) {
  jspb.Message.setOneofWrapperField(this, 5, proto.tutorial.Feature.oneofGroups_[0], value);
};


proto.tutorial.Feature.prototype.clearDoublechamfer = function() {
  this.setDoublechamfer(undefined);
};


