/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.tutorial.TcContourArcSegmentSerializable');

goog.require('jspb.Message');
goog.require('proto.tutorial.TcDoublePoseTuple');
goog.require('proto.tutorial.TsVectorSerializable');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.tutorial.TcContourArcSegmentSerializable = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.tutorial.TcContourArcSegmentSerializable.repeatedFields_, null);
};
goog.inherits(proto.tutorial.TcContourArcSegmentSerializable, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.tutorial.TcContourArcSegmentSerializable.displayName = 'proto.tutorial.TcContourArcSegmentSerializable';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.tutorial.TcContourArcSegmentSerializable.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.tutorial.TcContourArcSegmentSerializable.prototype.toObject = function(opt_includeInstance) {
  return proto.tutorial.TcContourArcSegmentSerializable.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.tutorial.TcContourArcSegmentSerializable} msg The msg instance to transform.
 * @return {!Object}
 */
proto.tutorial.TcContourArcSegmentSerializable.toObject = function(includeInstance, msg) {
  var f, obj = {
    ipocenterpoint: (f = msg.getIpocenterpoint()) && proto.tutorial.TsVectorSerializable.toObject(includeInstance, f),
    ipocenternormal: (f = msg.getIpocenternormal()) && proto.tutorial.TsVectorSerializable.toObject(includeInstance, f),
    iporadius: msg.getIporadius(),
    doubleposetupleList: jspb.Message.toObjectList(msg.getDoubleposetupleList(),
    proto.tutorial.TcDoublePoseTuple.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg
  }
  return obj;
};
}


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.tutorial.TcContourArcSegmentSerializable} The clone.
 */
proto.tutorial.TcContourArcSegmentSerializable.prototype.cloneMessage = function() {
  return /** @type {!proto.tutorial.TcContourArcSegmentSerializable} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional TsVectorSerializable IpoCenterPoint = 2;
 * @return {proto.tutorial.TsVectorSerializable}
 */
proto.tutorial.TcContourArcSegmentSerializable.prototype.getIpocenterpoint = function() {
  return /** @type{proto.tutorial.TsVectorSerializable} */ (
    jspb.Message.getWrapperField(this, proto.tutorial.TsVectorSerializable, 2));
};


/** @param {proto.tutorial.TsVectorSerializable|undefined} value  */
proto.tutorial.TcContourArcSegmentSerializable.prototype.setIpocenterpoint = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.tutorial.TcContourArcSegmentSerializable.prototype.clearIpocenterpoint = function() {
  this.setIpocenterpoint(undefined);
};


/**
 * optional TsVectorSerializable IpoCenterNormal = 3;
 * @return {proto.tutorial.TsVectorSerializable}
 */
proto.tutorial.TcContourArcSegmentSerializable.prototype.getIpocenternormal = function() {
  return /** @type{proto.tutorial.TsVectorSerializable} */ (
    jspb.Message.getWrapperField(this, proto.tutorial.TsVectorSerializable, 3));
};


/** @param {proto.tutorial.TsVectorSerializable|undefined} value  */
proto.tutorial.TcContourArcSegmentSerializable.prototype.setIpocenternormal = function(value) {
  jspb.Message.setWrapperField(this, 3, value);
};


proto.tutorial.TcContourArcSegmentSerializable.prototype.clearIpocenternormal = function() {
  this.setIpocenternormal(undefined);
};


/**
 * optional double IpoRadius = 4;
 * @return {number}
 */
proto.tutorial.TcContourArcSegmentSerializable.prototype.getIporadius = function() {
  return /** @type {number} */ (jspb.Message.getFieldProto3(this, 4, 0));
};


/** @param {number} value  */
proto.tutorial.TcContourArcSegmentSerializable.prototype.setIporadius = function(value) {
  jspb.Message.setField(this, 4, value);
};


/**
 * repeated TcDoublePoseTuple doublePoseTuple = 1;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<!proto.tutorial.TcDoublePoseTuple>}
 */
proto.tutorial.TcContourArcSegmentSerializable.prototype.getDoubleposetupleList = function() {
  return /** @type{!Array.<!proto.tutorial.TcDoublePoseTuple>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.tutorial.TcDoublePoseTuple, 1));
};


/** @param {Array.<!proto.tutorial.TcDoublePoseTuple>|undefined} value  */
proto.tutorial.TcContourArcSegmentSerializable.prototype.setDoubleposetupleList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


proto.tutorial.TcContourArcSegmentSerializable.prototype.clearDoubleposetupleList = function() {
  this.setDoubleposetupleList([]);
};


