/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.tutorial.TcDoublePoseTuple');

goog.require('jspb.Message');
goog.require('proto.tutorial.TsPoseSerializable');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.tutorial.TcDoublePoseTuple = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.tutorial.TcDoublePoseTuple, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.tutorial.TcDoublePoseTuple.displayName = 'proto.tutorial.TcDoublePoseTuple';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.tutorial.TcDoublePoseTuple.prototype.toObject = function(opt_includeInstance) {
  return proto.tutorial.TcDoublePoseTuple.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.tutorial.TcDoublePoseTuple} msg The msg instance to transform.
 * @return {!Object}
 */
proto.tutorial.TcDoublePoseTuple.toObject = function(includeInstance, msg) {
  var f, obj = {
    param: msg.getParam(),
    pose: (f = msg.getPose()) && proto.tutorial.TsPoseSerializable.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg
  }
  return obj;
};
}


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.tutorial.TcDoublePoseTuple} The clone.
 */
proto.tutorial.TcDoublePoseTuple.prototype.cloneMessage = function() {
  return /** @type {!proto.tutorial.TcDoublePoseTuple} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional double param = 1;
 * @return {number}
 */
proto.tutorial.TcDoublePoseTuple.prototype.getParam = function() {
  return /** @type {number} */ (jspb.Message.getFieldProto3(this, 1, 0));
};


/** @param {number} value  */
proto.tutorial.TcDoublePoseTuple.prototype.setParam = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional TsPoseSerializable pose = 2;
 * @return {proto.tutorial.TsPoseSerializable}
 */
proto.tutorial.TcDoublePoseTuple.prototype.getPose = function() {
  return /** @type{proto.tutorial.TsPoseSerializable} */ (
    jspb.Message.getWrapperField(this, proto.tutorial.TsPoseSerializable, 2));
};


/** @param {proto.tutorial.TsPoseSerializable|undefined} value  */
proto.tutorial.TcDoublePoseTuple.prototype.setPose = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.tutorial.TcDoublePoseTuple.prototype.clearPose = function() {
  this.setPose(undefined);
};


