/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.tutorial.TcRectangularHoleSerializable');

goog.require('jspb.Message');
goog.require('proto.tutorial.TsPoseSerializable');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.tutorial.TcRectangularHoleSerializable = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.tutorial.TcRectangularHoleSerializable, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.tutorial.TcRectangularHoleSerializable.displayName = 'proto.tutorial.TcRectangularHoleSerializable';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.tutorial.TcRectangularHoleSerializable.prototype.toObject = function(opt_includeInstance) {
  return proto.tutorial.TcRectangularHoleSerializable.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.tutorial.TcRectangularHoleSerializable} msg The msg instance to transform.
 * @return {!Object}
 */
proto.tutorial.TcRectangularHoleSerializable.toObject = function(includeInstance, msg) {
  var f, obj = {
    centerpoint: (f = msg.getCenterpoint()) && proto.tutorial.TsPoseSerializable.toObject(includeInstance, f),
    cornerradius: msg.getCornerradius(),
    length: msg.getLength(),
    width: msg.getWidth()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg
  }
  return obj;
};
}


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.tutorial.TcRectangularHoleSerializable} The clone.
 */
proto.tutorial.TcRectangularHoleSerializable.prototype.cloneMessage = function() {
  return /** @type {!proto.tutorial.TcRectangularHoleSerializable} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional TsPoseSerializable CenterPoint = 1;
 * @return {proto.tutorial.TsPoseSerializable}
 */
proto.tutorial.TcRectangularHoleSerializable.prototype.getCenterpoint = function() {
  return /** @type{proto.tutorial.TsPoseSerializable} */ (
    jspb.Message.getWrapperField(this, proto.tutorial.TsPoseSerializable, 1));
};


/** @param {proto.tutorial.TsPoseSerializable|undefined} value  */
proto.tutorial.TcRectangularHoleSerializable.prototype.setCenterpoint = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.tutorial.TcRectangularHoleSerializable.prototype.clearCenterpoint = function() {
  this.setCenterpoint(undefined);
};


/**
 * optional double CornerRadius = 2;
 * @return {number}
 */
proto.tutorial.TcRectangularHoleSerializable.prototype.getCornerradius = function() {
  return /** @type {number} */ (jspb.Message.getFieldProto3(this, 2, 0));
};


/** @param {number} value  */
proto.tutorial.TcRectangularHoleSerializable.prototype.setCornerradius = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional double Length = 3;
 * @return {number}
 */
proto.tutorial.TcRectangularHoleSerializable.prototype.getLength = function() {
  return /** @type {number} */ (jspb.Message.getFieldProto3(this, 3, 0));
};


/** @param {number} value  */
proto.tutorial.TcRectangularHoleSerializable.prototype.setLength = function(value) {
  jspb.Message.setField(this, 3, value);
};


/**
 * optional double Width = 4;
 * @return {number}
 */
proto.tutorial.TcRectangularHoleSerializable.prototype.getWidth = function() {
  return /** @type {number} */ (jspb.Message.getFieldProto3(this, 4, 0));
};


/** @param {number} value  */
proto.tutorial.TcRectangularHoleSerializable.prototype.setWidth = function(value) {
  jspb.Message.setField(this, 4, value);
};


