/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.tutorial.TcSegmentSerializable');

goog.require('jspb.Message');
goog.require('proto.tutorial.TcContourArcSegmentSerializable');
goog.require('proto.tutorial.TcContourLineSegmentSerializable');
goog.require('proto.tutorial.TcContourSplineSegmentSerializable');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.tutorial.TcSegmentSerializable = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.tutorial.TcSegmentSerializable.oneofGroups_);
};
goog.inherits(proto.tutorial.TcSegmentSerializable, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.tutorial.TcSegmentSerializable.displayName = 'proto.tutorial.TcSegmentSerializable';
}
/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.tutorial.TcSegmentSerializable.oneofGroups_ = [[1,2,3]];

/**
 * @enum {number}
 */
proto.tutorial.TcSegmentSerializable.SegmentCase = {
  SEGMENT_NOT_SET: 0,
  ARCSEGMENT: 1,
  LINESEGMENT: 2,
  SPLINESEGMENT: 3
};

/**
 * @return {proto.tutorial.TcSegmentSerializable.SegmentCase}
 */
proto.tutorial.TcSegmentSerializable.prototype.getSegmentCase = function() {
  return /** @type {proto.tutorial.TcSegmentSerializable.SegmentCase} */(jspb.Message.computeOneofCase(this, proto.tutorial.TcSegmentSerializable.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.tutorial.TcSegmentSerializable.prototype.toObject = function(opt_includeInstance) {
  return proto.tutorial.TcSegmentSerializable.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.tutorial.TcSegmentSerializable} msg The msg instance to transform.
 * @return {!Object}
 */
proto.tutorial.TcSegmentSerializable.toObject = function(includeInstance, msg) {
  var f, obj = {
    arcsegment: (f = msg.getArcsegment()) && proto.tutorial.TcContourArcSegmentSerializable.toObject(includeInstance, f),
    linesegment: (f = msg.getLinesegment()) && proto.tutorial.TcContourLineSegmentSerializable.toObject(includeInstance, f),
    splinesegment: (f = msg.getSplinesegment()) && proto.tutorial.TcContourSplineSegmentSerializable.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg
  }
  return obj;
};
}


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.tutorial.TcSegmentSerializable} The clone.
 */
proto.tutorial.TcSegmentSerializable.prototype.cloneMessage = function() {
  return /** @type {!proto.tutorial.TcSegmentSerializable} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional TcContourArcSegmentSerializable ArcSegment = 1;
 * @return {proto.tutorial.TcContourArcSegmentSerializable}
 */
proto.tutorial.TcSegmentSerializable.prototype.getArcsegment = function() {
  return /** @type{proto.tutorial.TcContourArcSegmentSerializable} */ (
    jspb.Message.getWrapperField(this, proto.tutorial.TcContourArcSegmentSerializable, 1));
};


/** @param {proto.tutorial.TcContourArcSegmentSerializable|undefined} value  */
proto.tutorial.TcSegmentSerializable.prototype.setArcsegment = function(value) {
  jspb.Message.setOneofWrapperField(this, 1, proto.tutorial.TcSegmentSerializable.oneofGroups_[0], value);
};


proto.tutorial.TcSegmentSerializable.prototype.clearArcsegment = function() {
  this.setArcsegment(undefined);
};


/**
 * optional TcContourLineSegmentSerializable LineSegment = 2;
 * @return {proto.tutorial.TcContourLineSegmentSerializable}
 */
proto.tutorial.TcSegmentSerializable.prototype.getLinesegment = function() {
  return /** @type{proto.tutorial.TcContourLineSegmentSerializable} */ (
    jspb.Message.getWrapperField(this, proto.tutorial.TcContourLineSegmentSerializable, 2));
};


/** @param {proto.tutorial.TcContourLineSegmentSerializable|undefined} value  */
proto.tutorial.TcSegmentSerializable.prototype.setLinesegment = function(value) {
  jspb.Message.setOneofWrapperField(this, 2, proto.tutorial.TcSegmentSerializable.oneofGroups_[0], value);
};


proto.tutorial.TcSegmentSerializable.prototype.clearLinesegment = function() {
  this.setLinesegment(undefined);
};


/**
 * optional TcContourSplineSegmentSerializable SplineSegment = 3;
 * @return {proto.tutorial.TcContourSplineSegmentSerializable}
 */
proto.tutorial.TcSegmentSerializable.prototype.getSplinesegment = function() {
  return /** @type{proto.tutorial.TcContourSplineSegmentSerializable} */ (
    jspb.Message.getWrapperField(this, proto.tutorial.TcContourSplineSegmentSerializable, 3));
};


/** @param {proto.tutorial.TcContourSplineSegmentSerializable|undefined} value  */
proto.tutorial.TcSegmentSerializable.prototype.setSplinesegment = function(value) {
  jspb.Message.setOneofWrapperField(this, 3, proto.tutorial.TcSegmentSerializable.oneofGroups_[0], value);
};


proto.tutorial.TcSegmentSerializable.prototype.clearSplinesegment = function() {
  this.setSplinesegment(undefined);
};


