/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.tutorial.TcWorkpieceSerializable');

goog.require('jspb.Message');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.tutorial.TcWorkpieceSerializable = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.tutorial.TcWorkpieceSerializable.repeatedFields_, null);
};
goog.inherits(proto.tutorial.TcWorkpieceSerializable, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.tutorial.TcWorkpieceSerializable.displayName = 'proto.tutorial.TcWorkpieceSerializable';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.tutorial.TcWorkpieceSerializable.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.tutorial.TcWorkpieceSerializable.prototype.toObject = function(opt_includeInstance) {
  return proto.tutorial.TcWorkpieceSerializable.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.tutorial.TcWorkpieceSerializable} msg The msg instance to transform.
 * @return {!Object}
 */
proto.tutorial.TcWorkpieceSerializable.toObject = function(includeInstance, msg) {
  var f, obj = {
    workpiecetype: msg.getWorkpiecetype(),
    documentid: msg.getDocumentid(),
    workpiecefeaturesList: jspb.Message.getField(msg, 3)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg
  }
  return obj;
};
}


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.tutorial.TcWorkpieceSerializable} The clone.
 */
proto.tutorial.TcWorkpieceSerializable.prototype.cloneMessage = function() {
  return /** @type {!proto.tutorial.TcWorkpieceSerializable} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional string WorkpieceType = 1;
 * @return {string}
 */
proto.tutorial.TcWorkpieceSerializable.prototype.getWorkpiecetype = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 1, ""));
};


/** @param {string} value  */
proto.tutorial.TcWorkpieceSerializable.prototype.setWorkpiecetype = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional string DocumentId = 2;
 * @return {string}
 */
proto.tutorial.TcWorkpieceSerializable.prototype.getDocumentid = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 2, ""));
};


/** @param {string} value  */
proto.tutorial.TcWorkpieceSerializable.prototype.setDocumentid = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * repeated int32 WorkpieceFeatures = 3;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<number>}
 */
proto.tutorial.TcWorkpieceSerializable.prototype.getWorkpiecefeaturesList = function() {
  return /** @type {!Array.<number>} */ (jspb.Message.getField(this, 3));
};


/** @param {Array.<number>} value  */
proto.tutorial.TcWorkpieceSerializable.prototype.setWorkpiecefeaturesList = function(value) {
  jspb.Message.setField(this, 3, value || []);
};


