/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.tutorial.TsMeshSerializable');

goog.require('jspb.Message');
goog.require('proto.tutorial.TsVectorSerializable');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.tutorial.TsMeshSerializable = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.tutorial.TsMeshSerializable.repeatedFields_, null);
};
goog.inherits(proto.tutorial.TsMeshSerializable, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.tutorial.TsMeshSerializable.displayName = 'proto.tutorial.TsMeshSerializable';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.tutorial.TsMeshSerializable.repeatedFields_ = [1,2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.tutorial.TsMeshSerializable.prototype.toObject = function(opt_includeInstance) {
  return proto.tutorial.TsMeshSerializable.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.tutorial.TsMeshSerializable} msg The msg instance to transform.
 * @return {!Object}
 */
proto.tutorial.TsMeshSerializable.toObject = function(includeInstance, msg) {
  var f, obj = {
    verticesList: jspb.Message.toObjectList(msg.getVerticesList(),
    proto.tutorial.TsVectorSerializable.toObject, includeInstance),
    indicesList: jspb.Message.getField(msg, 2)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg
  }
  return obj;
};
}


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.tutorial.TsMeshSerializable} The clone.
 */
proto.tutorial.TsMeshSerializable.prototype.cloneMessage = function() {
  return /** @type {!proto.tutorial.TsMeshSerializable} */ (jspb.Message.cloneMessage(this));
};


/**
 * repeated TsVectorSerializable Vertices = 1;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<!proto.tutorial.TsVectorSerializable>}
 */
proto.tutorial.TsMeshSerializable.prototype.getVerticesList = function() {
  return /** @type{!Array.<!proto.tutorial.TsVectorSerializable>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.tutorial.TsVectorSerializable, 1));
};


/** @param {Array.<!proto.tutorial.TsVectorSerializable>|undefined} value  */
proto.tutorial.TsMeshSerializable.prototype.setVerticesList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


proto.tutorial.TsMeshSerializable.prototype.clearVerticesList = function() {
  this.setVerticesList([]);
};


/**
 * repeated int32 Indices = 2;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<number>}
 */
proto.tutorial.TsMeshSerializable.prototype.getIndicesList = function() {
  return /** @type {!Array.<number>} */ (jspb.Message.getField(this, 2));
};


/** @param {Array.<number>} value  */
proto.tutorial.TsMeshSerializable.prototype.setIndicesList = function(value) {
  jspb.Message.setField(this, 2, value || []);
};


